export { default as SidebarLeft } from "./sidebar-left.svg.svelte"
export { default as SidebarRight } from "./sidebar-right.svg.svelte"
export { default as FolderClosed } from "./folder-closed.svg.svelte"
export { default as Folder } from "./folder.svg.svelte"
export { default as File } from "./file.svg.svelte"
